### ISSUE TITLE
inverted time check on sweepFromDeadStrategist

### ISSUE THREAD

**Issue by skeletor-spaceman** [flashfish0x/strategist_escrow#2]
https://github.com/flashfish0x/strategist_escrow/blob/14b21a93dadea6e2ed00a73e140b9ce0bfc42d28/contracts/StrategistEscrow.sol#L164

**Comment by skeletor-spaceman** [comment]
also minor issue with bad strategists initialization will bork clone. add a yChad setter for pendingStrategist if there is no strategist

also this is better for readability:
uint256 internal constant ONEMONTH = 1 years / 12;
uint256 internal constant FOURYEARS = 4 years;

**Comment by flashfish0x** [comment]
changes made:

https://github.com/flashfish0x/strategist_escrow/pull/3/files
